In [1]:
from sympy.solvers import solve
from sympy import Symbol
import math
import numpy as np
pi = 180 # degrees 

In [2]:
x = Symbol('x')

In [3]:
alpha = 30
beta = 60
delta = x

In [4]:
solve((8/math.sin(math.radians(alpha))) - (x/math.sin(math.radians(beta))), x)


[13.8564064605510]

In [5]:
class Semantic_Tri:
    def __init__(self, alpha=0, beta=0, delta=0, a=0, b=0, c=0, S=0, h=0):
        self.alpha = alpha
        self.beta = beta
        self.delta = delta
        self.a = a
        self.b = b
        self.c = c
        self.S = S
        self.h = h
        self.map = enumerate([alpha, beta, delta, a, b, c, S, h])
        
        # Cài đặt mạng ngữ nghĩa với số dòng <=> yếu tố của tam giác (đỉnh hình tròn)
        # số cột <=> công thức (đỉnh hình chữ nhật) => ma trận 8x5 theo bài 1 
        
        self.semantic_matrix = np.zeros((8, 5), dtype=int)
        idx = [(0, 0), (0, 3), 
               (1, 0), (1, 1), (1, 3),
               (2, 1), (2, 3),
               (3, 0), (3, 2),
               (4, 0), (4, 1), (4, 2),
               (5, 1), (5, 2), (5, 4),
               (6, 2), (6, 4),
               (7, 4)]
        for i, j in idx:
            self.semantic_matrix[i][j] = -1

In [26]:
test = Semantic_Tri()
test.semantic_matrix

array([[-1,  0,  0, -1,  0],
       [-1, -1,  0, -1,  0],
       [ 0, -1,  0, -1,  0],
       [-1,  0, -1,  0,  0],
       [-1, -1, -1,  0,  0],
       [ 0, -1, -1,  0, -1],
       [ 0,  0, -1,  0, -1],
       [ 0,  0,  0,  0, -1]])

In [7]:
# Thao tác “kích hoạt” một đỉnh hình tròn, ta đặt giá trị của toàn dòng ứng với yếu tố tam giác bằng 1.
def getMatrix(s=Semantic_Tri):
    for c, ele in s.map:
        if(ele != 0):
            for j in range(5):
                if s.semantic_matrix[c][j] == -1:
                    s.semantic_matrix[c][j]= 1
    return s.semantic_matrix

In [68]:
def is_activate(row_array):
    for i in range(5):
        if row_array[i] == -1:
            return False
    return True

In [69]:
def get_known_ele(col_array, idx):
    return np.where(col_array[:,idx] == 1)

In [ ]:
def heron()

In [70]:
def get_unk_el(col_array, idx):
    return np.where(col_array[:,idx] == -1)[0][0].astype(int)

In [92]:
def solution(goal='h'):
    s = Semantic_Tri(alpha=30, beta=60, a=8)
    #s = Semantic_Tri(alpha=30, beta=60)
    t = getMatrix(s)
    goal_map = ['alpha', 'beta', 'delta', 'a', 'b', 'c', 'S', 'h']
    goal_idx = goal_map.index(goal)
    
    stuck = False # Xử lí nếu thuật toán không đến đích
    
    print("goal_idx:", goal_idx, "goal_label:", goal_map[goal_idx])
    print(t)
    print("-------------------")
    
    while not stuck:
        stuck = True
        for k in range(5):
            print("k: " + str(k))
            idx_pos = np.where(t[:,k] == 1)
            pos = np.sum(np.take(t[:,k], idx_pos)) # yếu tố đã biết
            idx_neg = np.where(t[:,k] == -1)
            neg = np.sum(np.take(t[:,k], idx_neg)) # yếu tố chưa biết
            if np.count_nonzero(t[:,k]) - pos == 1: # điều kiện để kích hoạt yếu tố chưa biết: tổng các yếu tố - đã biết = 1 <=> chưa biết
                idx = get_unk_el(t, k)
                print("idx: " + str(idx), "label:" + goal_map[idx])
                # Kích hoạt: thay -1 trên dòng thành 1
                stuck = False
                for i in range(5):
                    if t[idx][i] == -1:
                        t[idx][i] = 1
                print(t)
            if is_activate(t[goal_idx,:]):
                stuck = True # True: tới đích thì dừng, False: đi tiếp cho tới khi tìm được kết quả
                print("Goal reached!")
                break

In [93]:
solution('c')

goal_idx: 5 goal_label: c
[[ 1  0  0  1  0]
 [ 1  1  0  1  0]
 [ 0 -1  0 -1  0]
 [ 1  0  1  0  0]
 [-1 -1 -1  0  0]
 [ 0 -1 -1  0 -1]
 [ 0  0 -1  0 -1]
 [ 0  0  0  0 -1]]
-------------------
k: 0
idx: 4 label:b
[[ 1  0  0  1  0]
 [ 1  1  0  1  0]
 [ 0 -1  0 -1  0]
 [ 1  0  1  0  0]
 [ 1  1  1  0  0]
 [ 0 -1 -1  0 -1]
 [ 0  0 -1  0 -1]
 [ 0  0  0  0 -1]]
k: 1
k: 2
k: 3
idx: 2 label:delta
[[ 1  0  0  1  0]
 [ 1  1  0  1  0]
 [ 0  1  0  1  0]
 [ 1  0  1  0  0]
 [ 1  1  1  0  0]
 [ 0 -1 -1  0 -1]
 [ 0  0 -1  0 -1]
 [ 0  0  0  0 -1]]
k: 4
k: 0
k: 1
idx: 5 label:c
[[ 1  0  0  1  0]
 [ 1  1  0  1  0]
 [ 0  1  0  1  0]
 [ 1  0  1  0  0]
 [ 1  1  1  0  0]
 [ 0  1  1  0  1]
 [ 0  0 -1  0 -1]
 [ 0  0  0  0 -1]]
Goal reached!
