In [1]:
from sympy.solvers import solve
from sympy import Symbol
import math
import numpy as np

In [2]:
# Khởi tạo class để áp dụng 5 công thức tam giác theo đề bài
class Formula:
    def __init__(self, alpha=0, beta=0, delta=0, a=0, b=0, c=0, S=0, h=0):
        self.alpha = alpha
        self.beta = beta
        self.delta = delta
        self.a = a
        self.b = b
        self.c = c
        self.S = S
        self.h = h
        self.f = None
    def apply_formula(self, f, goal='b'):
        x = Symbol('x', positive=True)
        if f == 0:
            if goal == 'a':
                self.f = solve((x/math.sin(math.radians(self.alpha)))-(self.b/math.sin(math.radians(self.beta))), x)
                self.a = np.float(self.f[0])
            if goal == 'b':
                self.f = solve((self.a/math.sin(math.radians(self.alpha)))-(x/math.sin(math.radians(self.beta))), x)
                self.b =  np.float(self.f[0])
            if goal == 'alpha':
                self.f = solve((self.a/math.sin(math.radians(x)))-(self.b/math.sin(math.radians(self.beta))), x)
                self.alpha =  np.float(self.f[0])
            if goal == 'beta':
                self.f = solve((self.a/math.sin(math.radians(self.alpha)))-(self.b/math.sin(math.radians(x))), x)
                self.beta =  np.float(self.f[0])
        if f == 1:
            if goal == 'b':
                self.f = solve((self.c/math.sin(math.radians(self.delta)))-(x/math.sin(math.radians(self.beta))), x)
                self.b =  np.float(self.f[0])
            if goal == 'c':
                self.f = solve((x/math.sin(math.radians(self.delta)))-(self.b/math.sin(math.radians(self.beta))), x)
                self.c =  np.float(self.f[0])
            if goal == 'beta':
                self.f = solve((self.c/math.sin(math.radians(self.delta)))-(self.b/math.sin(math.radians(x))), x)
                self.beta =  np.float(self.f[0])
            if goal == 'delta':
                self.f = solve((self.c/math.sin(math.radians(x)))-(self.b/math.sin(math.radians(self.beta))), x)
                self.delta =  np.float(self.f[0])
        if f == 2:
            p = (self.a + self.b + self.c)/2
            if goal == 'a':
                self.f = solve(self.S*self.S - p*(p-x)*(p-self.b)*(p-self.c), x)
                self.a =  np.float(self.f[0])
            if goal == 'b':
                self.f = solve(self.S*self.S - p*(p-self.a)*(p-x)*(p-self.c), x)
                self.b =  np.float(self.f[0])
            if goal == 'c':
                self.f = solve(self.S*self.S - p*(p-self.a)*(p-self.b)*(p-x), x)
                self.c =  np.float(self.f[0])
            if goal == 'S':
                self.f = solve(x*x - p*(p-self.a)*(p-self.b)*(p-self.c), x)
                self.S =  np.float(self.f[0])
        if f == 3:
            if goal == 'alpha':
                self.f = solve(x + self.beta + self.delta - 180, x)
                self.alpha =  np.float(self.f[0])
            if goal == 'beta':
                self.f = solve(self.alpha + x + self.delta - 180, x)
                self.beta =  np.float(self.f[0])
            if goal == 'delta':
                self.f = solve(self.alpha + self.beta + x - 180, x)
                self.delta =  np.float(self.f[0])
        if f == 4:
            if goal == 'h':
                self.f = solve(self.S - 0.5*x*self.c, x)
                self.h =  np.float(self.f[0])
            if goal == 'c':
                self.f = solve(self.S - 0.5*self.h*x, x)
                self.c =  np.float(self.f[0])
            if goal == 'S':
                self.f = solve(x - 0.5*self.h*self.c, x)
                self.S =  np.float(self.f[0])
#         print(self.alpha, self.beta, self.delta, self.a, self.b, self.c, self.S, self.h, self.f) # for debug
#         print(np.float(self.f[0]))
        return  np.float(self.f[0])

In [3]:
class Semantic_Tri:
    def __init__(self, alpha=0, beta=0, delta=0, a=0, b=0, c=0, S=0, h=0):
        self.alpha = alpha
        self.beta = beta
        self.delta = delta
        self.a = a
        self.b = b
        self.c = c
        self.S = S
        self.h = h
        self.map = enumerate([alpha, beta, delta, a, b, c, S, h])
        
        # Cài đặt mạng ngữ nghĩa với số dòng <=> yếu tố của tam giác (đỉnh hình tròn)
        # số cột <=> công thức (đỉnh hình chữ nhật) => ma trận 8x5 theo bài 1 
        
        self.semantic_matrix = np.zeros((8, 5), dtype=int)
        idx = [(0, 0), (0, 3), 
               (1, 0), (1, 1), (1, 3),
               (2, 1), (2, 3),
               (3, 0), (3, 2),
               (4, 0), (4, 1), (4, 2),
               (5, 1), (5, 2), (5, 4),
               (6, 2), (6, 4),
               (7, 4)]
        for i, j in idx:
            self.semantic_matrix[i][j] = -1

In [5]:
# Thao tác “kích hoạt” một đỉnh hình tròn, ta đặt giá trị của toàn dòng ứng với yếu tố tam giác bằng 1.
def getMatrix(s=Semantic_Tri):
    for c, ele in s.map:
        if(ele != 0):
            for j in range(5):
                if s.semantic_matrix[c][j] == -1:
                    s.semantic_matrix[c][j]= 1
    return s.semantic_matrix

In [6]:
def is_activate(row_array):
    for i in range(5):
        if row_array[i] == -1:
            return False
    return True

In [7]:
def get_known_ele(col_array, idx):
    return np.where(col_array[:,idx] == 1)

In [8]:
def get_unk_ele(col_array, idx):
    return np.where(col_array[:,idx] == -1)[0][0].astype(int)

In [9]:
def solution(alpha=0, beta=0, delta=0, a=0, b=0, c=0, S=0, h=0, goal='h'):
    s = Semantic_Tri(alpha=alpha, beta=beta, delta=delta, a=a, b=b, c=c, S=S, h=h)
    #s = Semantic_Tri(alpha=30, beta=60)
    t = getMatrix(s)
    goal_map = ['alpha', 'beta', 'delta', 'a', 'b', 'c', 'S', 'h']
    goal_idx = goal_map.index(goal)
    
    #Formula
    my_F = Formula(alpha=alpha, beta=beta, delta=delta, a=a, b=b, c=c, S=S, h=h)
    
    stuck = False # Xử lí nếu thuật toán không đến đích
    
    print("goal_idx:", goal_idx, "goal_label:", goal_map[goal_idx])
    print(t)
    print("-------------------")
    
    while not stuck:
        stuck = True
        for k in range(5):
#             print("k: " + str(k))
            idx_pos = get_known_ele(t,k)
            pos = np.sum(np.take(t[:,k], idx_pos)) # yếu tố đã biết
#             idx_neg = np.where(t[:,k] == -1)
#             neg = np.sum(np.take(t[:,k], idx_neg)) # yếu tố chưa biết
            if np.count_nonzero(t[:,k]) - pos == 1: # điều kiện để kích hoạt yếu tố chưa biết: tổng các yếu tố - đã biết = 1 <=> chưa biết
                idx = get_unk_ele(t, k)
#                 print("idx: " + str(idx), "label:" + goal_map[idx])
                # Kích hoạt: thay -1 trên dòng thành 1
                stuck = False
                for i in range(5):
                    if t[idx][i] == -1:
                        t[idx][i] = 1
                # ------------------------------
                res = my_F.apply_formula(k, goal_map[idx])
                print("Dùng công thức: "+ "(" + str(k+1) + ") để tính " + str(goal_map[idx]) + " = " +str(res))
                
                
                # ------------------------------
                print(t)
            if is_activate(t[goal_idx,:]):
                stuck = True # True: tới đích thì dừng, False: đi tiếp cho tới khi tìm được kết quả
                print("Goal reached!")
                break

In [10]:
solution(a=6,b=8,c=10,goal='S')

goal_idx: 6 goal_label: S
[[ 1  0  0  1  0]
 [ 1  1  0  1  0]
 [ 0 -1  0 -1  0]
 [ 1  0  1  0  0]
 [ 1  1  1  0  0]
 [ 0  1  1  0  1]
 [ 0  0 -1  0 -1]
 [ 0  0  0  0 -1]]
-------------------


TypeError: can't convert expression to float